#!/bin/bash

grep READING /var/log/morningstar.log > morningstar-all.csv
(cat header.csv; grep glacier morningstar-all.csv) > morningstar-glacier.csv
(cat header.csv; grep lodge morningstar-all.csv) > morningstar-lodge.csv
