#!/bin/sh

function log() {
    /usr/bin/logger -t local-backup "$@"
}

log "Performing local backup..."

mkdir -p /backup
umount -f /backup

if [ -e /dev/sda1 ]; then
    mount /dev/sda1 /backup
    if [ "$?" == 0 ]; then
        rsync -zvua --progress /data/geophone/ /backup/geophone/ | /usr/bin/logger -t local-backup 2>&1
        rsync -zvua --progress /data/obsidian/ /backup/obsidian/ | /usr/bin/logger -t local-backup 2>&1
        umount -f /backup
        log "Local backup done."
    else
        log "FATAL: /dev/sda1 unmountable. "
        exit 2
    fi
else
    log "FATAL: /dev/sda1 is the wrong type."
    exit 2
fi
