#!/bin/bash

sudo docker run -d --name upload-geo --restart=always -v /data:/app/data conservify/go-uploader /app/uploader --url https://calgary.ocr.nyc/send --pattern "([^\.]+)_(\d{8})_(\d{6}).bin" --watch --token "zddgXMjr_YI2e87G0mch6tXHMupLGZ6PZ58mHOSdqJtQ566PJj8mzQ" --archive /app/data

sudo docker run -d --name upload-obs --restart=always -v /data:/app/data conservify/go-uploader /app/uploader --url http://code.conservify.org/geophones --pattern "(\d{14}).dig1.ch1.KMI.evt" --watch --token "zddgXMjr_YI2e87G0mch6tXHMupLGZ6PZ58mHOSdqJtQ566PJj8mzQ" /app/data/obsidian
