#!/bin/bash

mount /dev/md0 /data

/etc/init.d/logmein-hamachi start

/home/pi/geophones/lodge/routing
su pi -c "/home/pi/geophones/lodge/forward-rock-http"
su pi -c "/home/pi/geophones/lodge/forward-rock-ssh"

export DOCKER_API_VERSION=1.22

/home/pi/geophones/resilience/resilience --disable-reboot 8.8.8.8 >> /data/resilience.log 2>&1
