#!/bin/sh
# -*- mode: sh -*-

LAN_TARGET=192.168.5.1
WAN_TARGET=192.168.5.1

function reachable() {
    IP=$1

    ping -c 1 $IP
    if [ "$?" == 0 ]; then
        return 2
    fi

    ping -c 1 $IP
    if [ "$?" == 0 ]; then
        return 2
    fi

    ping -c 1 $IP
    if [ "$?" == 0 ]; then
        return 2
    fi

    return 0
}

if reachable $WAN_TARGET; then
    echo "WAN unreachable"

    if reachable $LAN_TARGET; then
        echo "LAN unreachable."
        exit 2
    else
        echo "LAN reachable, assuming upstream networking error."
        exit 0
    fi
else
    echo "WAN reachable."
    exit 0
fi